table Buckets
	lineageTag: 898f55d7-9a76-43c9-8530-32862b68a953

	column Bucket
		dataType: string
		lineageTag: 323fe867-0e98-4228-b706-5e5d8e16b56f
		summarizeBy: none
		sourceColumn: Bucket
		sortByColumn: Category

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: int64
		formatString: 0
		lineageTag: 7aa7b563-8500-49fb-a454-41a21906d3bf
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Bucket Sort'
		dataType: int64
		formatString: 0
		lineageTag: 299eb679-e06b-43e3-90e8-4a30f0ef68f7
		summarizeBy: none
		sourceColumn: Bucket Sort

		annotation SummarizationSetBy = Automatic

	column Bucket_2
		dataType: string
		lineageTag: a4e19b8f-e5fc-4028-8729-bab1ca95e67e
		summarizeBy: none
		sourceColumn: Bucket_2
		sortByColumn: 'Bucket Sort'

		annotation SummarizationSetBy = Automatic

	partition Buckets-57fac719-6790-4d47-a1d4-17f80f110e7f = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("PctLDoAwCATQu7AuCVo+epbalfEI3l8okQUkzBvGgOsl6ncnaLDH2nwqm21AJ2T2MCulLEtZUE4P/fRKqeavEmqoxi+XWqoRWqiFSumRuo7nCFtL/0Jkc34=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [Bucket = _t, Category = _t, #"Bucket Sort" = _t, Bucket_2 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Bucket", type text}, {"Category", Int64.Type}, {"Bucket Sort", Int64.Type}, {"Bucket_2", type text}})
				in
				    #"Changed Type"

	annotation PBI_QueryRelationships = {"columnCount":4,"keyColumnNames":[],"queryRelationships":[],"columnIdentities":["Section1/Buckets/Changed Type.{Bucket,0}","Section1/Buckets/Changed Type.{Category,1}","Section1/Buckets/Changed Type.{Bucket Sort,2}","Section1/Buckets/Changed Type.{Bucket_2,3}"],"ColumnCount":4,"KeyColumnNames":[],"ColumnIdentities":["Section1/Buckets/Changed Type.{Bucket,0}","Section1/Buckets/Changed Type.{Category,1}","Section1/Buckets/Changed Type.{Bucket Sort,2}","Section1/Buckets/Changed Type.{Bucket_2,3}"],"RelationshipInfo":[]}

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

