table 'Extra Year'
	lineageTag: 805f6912-6c51-406f-9351-bdf9c32642ed

	measure 'Extra year Value' = SELECTEDVALUE('Extra Year'[Extra year])
		lineageTag: 8b1b27f5-1ff1-4b9b-83ca-1270a6a4ed3c

	column 'Extra year'
		dataType: int64
		formatString: 0
		lineageTag: 93344145-9253-437c-a9ee-7297e02627c0
		summarizeBy: none
		isDataTypeInferred
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Extra Year-ff2f05c6-1996-43f1-8aa8-329d7d354603' = calculated
		mode: import
		source = GENERATESERIES(1800, 2017, 1)

