table Flags
	lineageTag: fae08b9e-4b3a-4989-8cc9-8c619104619b

	column 'Country Code'
		dataType: string
		lineageTag: af6ad719-2065-4dde-94d4-bfdab7569301
		summarizeBy: none
		sourceColumn: Country Code

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 2a511b51-f3fe-4910-aebe-b8b4c74753ee
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column 'Images File Name'
		dataType: string
		lineageTag: 429f212e-52ca-4559-ab38-7e22696ae98b
		summarizeBy: none
		sourceColumn: Images File Name

		annotation SummarizationSetBy = Automatic

	column ImageURL
		dataType: string
		lineageTag: a9646908-d32e-47c5-8f54-e73e4670545c
		summarizeBy: none
		sourceColumn: ImageURL

		annotation SummarizationSetBy = Automatic

	partition Flags-d6fea5e1-52e1-40ac-a570-cd8b6fe332e4 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Justyna\OneDrive - Microsoft\Gartner\BI Bake Off\London\Country_Flags.csv"),[Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Removed Columns" = Table.RemoveColumns(#"Promoted Headers",{""})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

