table Legend
	lineageTag: d32cabf6-336a-4f5b-a12d-d94097be9a05

	column Metric
		dataType: string
		lineageTag: 0439d427-2309-4467-bcfc-c5d9ef898089
		summarizeBy: none
		sourceColumn: Metric

		annotation SummarizationSetBy = Automatic

	column Bubble01
		dataType: int64
		formatString: 0
		lineageTag: 334832d1-5da7-453b-aee9-b4af8827f37d
		summarizeBy: sum
		sourceColumn: Bubble01

		annotation SummarizationSetBy = Automatic

	column Bubble02
		dataType: int64
		formatString: 0
		lineageTag: 6b3dad39-de99-4478-bbb8-ba861e26569c
		summarizeBy: sum
		sourceColumn: Bubble02

		annotation SummarizationSetBy = Automatic

	column Bubble03
		dataType: int64
		formatString: 0
		lineageTag: ae41345c-31b8-4151-bf26-95cca2477596
		summarizeBy: sum
		sourceColumn: Bubble03

		annotation SummarizationSetBy = Automatic

	column Bubble04
		dataType: int64
		formatString: 0
		lineageTag: b7c7a955-7507-419e-a808-6bc595851903
		summarizeBy: sum
		sourceColumn: Bubble04

		annotation SummarizationSetBy = Automatic

	column Bubble05
		dataType: int64
		formatString: 0
		lineageTag: ec512044-7881-49e7-9c21-e1d181445707
		summarizeBy: sum
		sourceColumn: Bubble05

		annotation SummarizationSetBy = Automatic

	partition Legend-65f60753-9014-41bd-a4ba-599ebcf69f8e = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8slMS1VwrShITS5JzEuuVNCITE0sKtZU0lEyNgASJqZAwgzEMgcRFgZKsbEA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [Metric = _t, Bubble01 = _t, Bubble02 = _t, Bubble03 = _t, Bubble04 = _t, Bubble05 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Metric", type text}, {"Bubble01", Int64.Type}, {"Bubble02", Int64.Type}, {"Bubble03", Int64.Type}, {"Bubble04", Int64.Type}, {"Bubble05", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_QueryRelationships = {"columnCount":6,"keyColumnNames":[],"queryRelationships":[],"columnIdentities":["Section1/Legend/Changed Type.{Metric,0}","Section1/Legend/Changed Type.{Bubble01,1}","Section1/Legend/Changed Type.{Bubble02,2}","Section1/Legend/Changed Type.{Bubble03,3}","Section1/Legend/Changed Type.{Bubble04,4}","Section1/Legend/Changed Type.{Bubble05,5}"],"ColumnCount":6,"KeyColumnNames":[],"ColumnIdentities":["Section1/Legend/Changed Type.{Metric,0}","Section1/Legend/Changed Type.{Bubble01,1}","Section1/Legend/Changed Type.{Bubble02,2}","Section1/Legend/Changed Type.{Bubble03,3}","Section1/Legend/Changed Type.{Bubble04,4}","Section1/Legend/Changed Type.{Bubble05,5}"],"RelationshipInfo":[]}

	annotation PBI_ResultType = Table

