table Metrics
	lineageTag: 6a0d62f0-182b-47d5-b38a-ef6fdf40dddc

	measure 'Life Expectancy 2' = ROUNDUP(AVERAGE(Indicators[Life expectancy (yrs)]),0)
		formatString: 0
		lineageTag: 9dc7d6fe-bd62-4441-9caa-f6f748f1d59a

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Life Expectancy YoY% 2' =
			
			IF(
				ISFILTERED('Year'[Date]),
				ERROR("Time intelligence quick measures wwwwv can only be grouped or filtered by the Power BI-provided date hierarchy or primary date column."),
				VAR __PREV_YEAR = CALCULATE(AVERAGE(Indicators[Life expectancy (yrs)]), DATEADD('Year'[Date].[Date], -14, YEAR))
				RETURN
					DIVIDE(AVERAGE(Indicators[Life expectancy (yrs)]) - __PREV_YEAR, __PREV_YEAR)
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 4992697c-2547-4bbe-bb64-960f34ad6531

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "YearOverYear"
				}

	measure 'Malaria Cases Change' = If(not(isblank(CALCULATE(AVERAGE(Indicators[Malaria - number of reported confirmed cases]), 'Year'[Year] = 2016))) && not(isblank(CALCULATE(AVERAGE(Indicators[Malaria - number of reported confirmed cases]), 'Year'[Year] = 2010))), CALCULATE(AVERAGE(Indicators[Malaria - number of reported confirmed cases]), 'Year'[Year] = 2016) - CALCULATE(AVERAGE(Indicators[Malaria - number of reported confirmed cases]), 'Year'[Year] = 2010))
		lineageTag: c55bd9d9-6b1e-4e7d-a371-1843a2a06b3a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'GDP Change' = If(not(isblank(CALCULATE(AVERAGE(Indicators[GDP per capita (US $)]), 'Year'[Year] = 2016))) && not(isblank(CALCULATE(AVERAGE(Indicators[GDP per capita (US $)]), 'Year'[Year] = 2010))), CALCULATE(AVERAGE(Indicators[GDP per capita (US $)]), 'Year'[Year] = 2016) - CALCULATE(AVERAGE(Indicators[GDP per capita (US $)]), 'Year'[Year] = 2010))
		lineageTag: 67a8d060-4d02-45eb-9cbb-70a43af51ea4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Income Change' = IF(NOT(ISBLANK(CALCULATE(AVERAGE(Indicators[Income share held by lowest 20%]), 'Year'[Year] = 2016))) && NOT(ISBLANK(CALCULATE(AVERAGE(Indicators[Income share held by lowest 20%]), 'Year'[Year] = 2010 ))), CALCULATE(AVERAGE(Indicators[Income share held by lowest 20%]), 'Year'[Year] = 2016) - CALCULATE(AVERAGE(Indicators[Income share held by lowest 20%]), 'Year'[Year] = 2010))
		lineageTag: 3ec9159f-b32c-4fd0-8561-48806ff97bad

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'GDP Old' = CALCULATE(AVERAGE(Indicators[GDP per capita (US $)]), 'Year'[Year] = 2016) - CALCULATE(AVERAGE(Indicators[GDP per capita (US $)]), 'Year'[Year] = 2010)
		lineageTag: c237df6c-8115-4335-be1c-09a5a5cea2dc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Neonatal mortality' = If(not(isblank(CALCULATE(AVERAGE(Indicators[Neonatal mortality rate (per 1000 live births)]), 'Year'[Year] = 2016))) && not(isblank(CALCULATE(AVERAGE(Indicators[Neonatal mortality rate (per 1000 live births)]), 'Year'[Year] = 2010))), CALCULATE(AVERAGE(Indicators[Neonatal mortality rate (per 1000 live births)]), 'Year'[Year] = 2016) - CALCULATE(AVERAGE(Indicators[Neonatal mortality rate (per 1000 live births)]), 'Year'[Year] = 2010))
		formatString: 0
		lineageTag: e601f7b5-5c5b-48f9-919c-dc100ffb942e

	measure 'Maternal Mortality Change' = If(not(isblank( CALCULATE(AVERAGE(Indicators[Maternal mortality ratio (per 100 000 live births)]), 'Year'[Year] = 2016))) && not(isblank(CALCULATE(AVERAGE(Indicators[Maternal mortality ratio (per 100 000 live births)]), 'Year'[Year] = 2010))), CALCULATE(AVERAGE(Indicators[Maternal mortality ratio (per 100 000 live births)]), 'Year'[Year] = 2016) - CALCULATE(AVERAGE(Indicators[Maternal mortality ratio (per 100 000 live births)]), 'Year'[Year] = 2010))
		lineageTag: 55fe32e9-95b3-4f02-947a-dd1836578a1c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Pupil Teacher Ratio Change' = If(not(isblank( CALCULATE(AVERAGE(Indicators[Pupil-teacher ratio in lower secondary education (headcount basis)]), 'Year'[Year] = 2016))) && (not(isblank(CALCULATE(AVERAGE(Indicators[Pupil-teacher ratio in lower secondary education (headcount basis)]), 'Year'[Year] = 2010)))), CALCULATE(AVERAGE(Indicators[Pupil-teacher ratio in lower secondary education (headcount basis)]), 'Year'[Year] = 2016) - CALCULATE(AVERAGE(Indicators[Pupil-teacher ratio in lower secondary education (headcount basis)]), 'Year'[Year] = 2010))
		lineageTag: d2936c1a-e9c5-4f13-aaf5-cbe0e14e2377

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Tuberculosis Incidents' = If(not(isblank(CALCULATE(AVERAGE(Indicators[Incidence of tuberculosis (per 100 000 population per year)]), 'Year'[Year] = 2016))) && not(isblank( CALCULATE(AVERAGE(Indicators[Incidence of tuberculosis (per 100 000 population per year)]), 'Year'[Year] = 2010))), CALCULATE(AVERAGE(Indicators[Incidence of tuberculosis (per 100 000 population per year)]), 'Year'[Year] = 2016) - CALCULATE(AVERAGE(Indicators[Incidence of tuberculosis (per 100 000 population per year)]), 'Year'[Year] = 2010))
		lineageTag: f1015b62-36a3-4b93-b7d0-d6c8fd82deea

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Immunizations = CALCULATE(DIVIDE(DIVIDE((AVERAGE(Indicators[Hib (Hib3) immunization coverage among 1-year-olds (%)])+AVERAGE(Indicators[Measles-containing-vaccine first-dose (MCV1) immunization coverage among 1-year-olds (%)])+AVERAGE(Indicators[Hepatitis B (HepB3) immunization coverage among 1-year-olds (%)])+AVERAGE(Indicators[Diphtheria tetanus toxoid and pertussis (DTP3) immunization coverage among 1-year-olds (%)])),4,0),100,0), ALL('Year'[Year]))
		formatString: 0%;-0%;0%
		lineageTag: 9fd9a425-a016-4849-ad5c-20f8f6f5b0cc

	measure 'Cholera Fatality Rate (%)' = DIVIDE(CALCULATE(AVERAGE(Indicators[Cholera case fatality rate]),ALL('Year'[Year])),100,0)
		formatString: 0%;-0%;0%
		lineageTag: 73cad856-dc4f-4548-883b-3b0bc6284a03

	measure 'Goverment Expenditure on Health (%)' = DIVIDE(CALCULATE(AVERAGE(Indicators[General government expenditure on health as a percentage of total expenditure on health]),ALL('Year'[Year])),100,0)
		formatString: 0%;-0%;0%
		lineageTag: 35e8b29b-671d-405b-836f-be5f976d0490

	measure 'GDP Per Capita (USD)' = CALCULATE(AVERAGE(Indicators[GDP per capita (current US$)]),ALL('Year'[Year]))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 54a23105-5644-46ec-9060-0c2c68f7483f

	measure 'GDP Black' = IF([GDPT]>=10000,[GDP Per Capita (USD)],"")
		formatString: 0
		lineageTag: f2086d7f-c38d-4cfe-839c-1a05d0df2c3b

	measure 'GDP Goal' = 10000
		formatString: #,0
		lineageTag: b5491481-4f27-42d0-a56c-0f6b8dad85af

	measure 'last year' = LASTDATE('Year'[Date])
		formatString: General Date
		lineageTag: 089d4854-01a4-4bce-af5b-ea75f10d98d0

	measure 'GEH Black' = IF([GEHT]>=.5,[Goverment Expenditure on Health (%)],"")
		formatString: 0%;-0%;0%
		lineageTag: 75bca589-3de9-4450-a4eb-c87287597861

	measure 'GEH Goal' = .6
		formatString: 0%;-0%;0%
		lineageTag: 3c0b0c93-a032-4550-a247-e2c1ac085afd

	measure 'IMM Black' = IF([IMMT]>=.7,[Immunizations],"")
		formatString: 0
		lineageTag: 171d862e-fb2f-47c1-9bc4-802db2d36948

	measure 'IMM Red' = .85
		formatString: 0%;-0%;0%
		lineageTag: ccfdb066-a19e-41b7-ba60-6618f99ce458

	measure 'CFR Red' = .02
		formatString: 0%;-0%;0%
		lineageTag: 3b9efdfd-3a12-45a3-97a5-224b53b8d9cc

	measure 'CFR Black' = IF([CFRT]<2,[Cholera Fatality Rate (%)],"")
		lineageTag: e327b49f-bc69-490a-bd1a-012f5ed3ba6c

	measure 'Child Mortality Rate' = AVERAGE(Indicators[Under-five mortality rate (probability of dying by age 5 per 1000 live births)])
		formatString: #,0.00
		lineageTag: e91f50f7-7f27-43bd-9c15-ca41f7e9dcdc

	measure GDPT =
			
			var LatestYearWithGDP = LASTNONBLANK(ALL(Years[Years]), [GDP Per Capita (USD)])
			return CALCULATE([GDP Per Capita (USD)], LatestYearWithGDP)
		formatString: 0
		lineageTag: 604e36b7-5775-41e5-b8cf-5ae209aab07c

	measure GEHT =
			
			var LatestYearWithGDP = LASTNONBLANK(ALL(Years[Years]), [Goverment Expenditure on Health (%)])
			return CALCULATE([Goverment Expenditure on Health (%)], LatestYearWithGDP)
		lineageTag: 5a1b60e2-dc9d-4d22-9e5e-31927be40d56

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure IMMT =
			
			var LatestYearWithGDP = LASTNONBLANK(ALL(Years[Years]), [Immunizations])
			return CALCULATE([Immunizations], LatestYearWithGDP)
		lineageTag: d6192b5c-3540-4426-912d-8f43694de187

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure CFRT =
			
			var LatestYearWithGDP = LASTNONBLANK(ALL(Years[Years]), [Cholera Fatality Rate (%)])
			return CALCULATE([Cholera Fatality Rate (%)], LatestYearWithGDP)
		lineageTag: 81b0ffd9-370d-42b9-816d-6ac56aeaa4f9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure LEXT =
			
			var LatestYearWithGDP = LASTNONBLANK(ALL(Years[Years]), [Life Expectancy 2])
			return CALCULATE([Life Expectancy 2], LatestYearWithGDP)
		lineageTag: dba9ea41-9195-44ed-b97f-786e7924a76b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure CLE =
			
			var LatestYearWithGDP = LASTNONBLANK('Years'[Years], [Child Mortality Rate])
			return CALCULATE(DISTINCTCOUNT(Indicators[Country Code]), LatestYearWithGDP)
		formatString: 0
		lineageTag: f17c4eae-b194-4824-9188-a4b3311c9d5b

	measure LE-100 = 100-[Life Expectancy 2]
		lineageTag: 7064d5c0-960f-46c8-af59-b833e7660bbf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Health = "tekst:"
		lineageTag: 5bbd801c-50a6-4338-a38e-55c9ea7b982c

	measure 'Health Expenditure' = SUM(Indicators[Community health workers density (per 10 000 population)])+ SUM(Indicators[Per capita total expenditure on health (PPP int. $)])
		formatString: 0
		lineageTag: c914fdbb-0629-4546-b496-a0287ec18bb7

	measure LE-Goal = 80
		formatString: 0
		lineageTag: 1efe9e8d-9622-448e-b1fa-a39761968b83

	measure 'Life Expectancy For Chart' = CALCULATE([Life Expectancy 2], TREATAS(VALUES('Extra Year'[Extra year]), 'Year'[Year]), ALL('Years'))
		lineageTag: 6aac4c79-f16e-4373-ac80-0777a45f6924

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Life Expectancy Colour Coding For Chart' = ```
			
			SWITCH(
			    TRUE(),
			    SELECTEDVALUE('Years'[Years])<SELECTEDVALUE('Extra Year'[Extra year]), "#dddddddd", 
			    [Life Expectancy For Chart]<=30, "#D64550",
			    [Life Expectancy For Chart]<=45, "#DE6A3E",
			    [Life Expectancy For Chart]<=60, "#E89928",
			    [Life Expectancy For Chart]<=70, "#E89928",
			    [Life Expectancy For Chart]<=80, "#65606A",
			    "#474A7D")
			```
		lineageTag: 1574c8cd-0cf3-468e-a218-a0122290c669

	measure 'Life Expectancy label' = CONCATENATE("Life Expectancy: ", CONCATENATE(FORMAT([Life Expectancy 2],"#,##"), " test"))
		lineageTag: 143a3ded-edda-4601-85fc-3fb4c6febfd7

	measure 'Water Services Access' = If(not(isblank(CALCULATE(AVERAGE(Indicators[People using at least basic drinking water services (% of population)]), 'Year'[Year] = 2016))) && not(isblank(CALCULATE(AVERAGE(Indicators[People using at least basic drinking water services (% of population)]), 'Year'[Year] = 2010))), CALCULATE(AVERAGE(Indicators[People using at least basic drinking water services (% of population)]), 'Year'[Year] = 2016) - CALCULATE(AVERAGE(Indicators[People using at least basic drinking water services (% of population)]), 'Year'[Year] = 2010))
		lineageTag: 51750718-02cf-4d4c-9156-08fa27581cc8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Measles Vaccine' = If(not(isblank(CALCULATE(AVERAGE(Indicators[Measles-containing-vaccine first-dose (MCV1) immunization coverage among 1-year-olds (%)]), 'Year'[Year] = 2016))) && not(isblank(CALCULATE(AVERAGE(Indicators[Measles-containing-vaccine first-dose (MCV1) immunization coverage among 1-year-olds (%)]), 'Year'[Year] = 2010))), CALCULATE(AVERAGE(Indicators[Measles-containing-vaccine first-dose (MCV1) immunization coverage among 1-year-olds (%)]), 'Year'[Year] = 2016) - CALCULATE(AVERAGE(Indicators[Measles-containing-vaccine first-dose (MCV1) immunization coverage among 1-year-olds (%)]), 'Year'[Year] = 2010))
		lineageTag: ef40b541-5297-44e5-8b2d-605c45339b7c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Hib3 Immunizations' = If(not(isblank(CALCULATE(AVERAGE(Indicators[Hib (Hib3) immunization coverage among 1-year-olds (%)]), 'Year'[Year] = 2016))) && not(isblank(CALCULATE(AVERAGE(Indicators[Hib (Hib3) immunization coverage among 1-year-olds (%)]), 'Year'[Year] = 2010))), CALCULATE(AVERAGE(Indicators[Hib (Hib3) immunization coverage among 1-year-olds (%)]), 'Year'[Year] = 2016) - CALCULATE(AVERAGE(Indicators[Hib (Hib3) immunization coverage among 1-year-olds (%)]), 'Year'[Year] = 2010))
		lineageTag: 4254a74e-88b7-4a43-9d72-f8bcc51a18e0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Column1
		dataType: string
		isHidden
		lineageTag: e632fa99-bfc1-414c-b9ea-fe028171427b
		summarizeBy: none
		sourceColumn: Column1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Metrics-1c88d61f-baf0-4391-90c4-6c44c1e7525d = m
		mode: import
		source =
				let
				    Source = """""",
				    #"Converted to Table" = #table(1, {{Source}})
				in
				    #"Converted to Table"

	annotation PBI_QueryRelationships = {"columnCount":1,"keyColumnNames":[],"queryRelationships":[],"columnIdentities":["Section1/Metrics/Converted to Table.{Column1,0}"],"ColumnCount":1,"KeyColumnNames":[],"ColumnIdentities":["Section1/Metrics/Converted to Table.{Column1,0}"],"RelationshipInfo":[]}

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

