table 'Variance Analysis'
	lineageTag: 5b5d8b4f-74ef-4fb7-806f-b04dfac6bf0c

	column 'Maternal Mortality Change'
		dataType: int64
		formatString: 0
		lineageTag: 233aa59b-82c0-4af5-a2dc-088f7b03db28
		summarizeBy: sum
		sourceColumn: Maternal Mortality Change

		annotation SummarizationSetBy = Automatic

	column 'Maternal Mortality'
		dataType: string
		lineageTag: 72b3abea-c2f3-4b1c-95ff-8852595a73e1
		summarizeBy: none
		sourceColumn: Maternal Mortality

		annotation SummarizationSetBy = Automatic

	column 'Malaria Cases Change'
		dataType: int64
		formatString: 0
		lineageTag: 301917c3-43cf-4cd0-8597-bd3cc04e4c50
		summarizeBy: sum
		sourceColumn: Malaria Cases Change

		annotation SummarizationSetBy = Automatic

	column 'Malaria Cases'
		dataType: string
		lineageTag: dc71a694-cd90-47ca-a196-abf2a6670902
		summarizeBy: none
		sourceColumn: Malaria Cases

		annotation SummarizationSetBy = Automatic

	column 'Neonatal Mortality Change'
		dataType: int64
		formatString: 0
		lineageTag: e182baa7-0c0a-49a7-bde2-debe44a38f6d
		summarizeBy: sum
		sourceColumn: Neonatal Mortality Change

		annotation SummarizationSetBy = Automatic

	column 'Neonatal Mortality'
		dataType: string
		lineageTag: 4e92b5c9-eea8-4bf8-aeb5-5ffe451fc9be
		summarizeBy: none
		sourceColumn: Neonatal Mortality

		annotation SummarizationSetBy = Automatic

	column 'GDP Change'
		dataType: double
		lineageTag: 7997ad92-e1e6-4419-a132-408f9b912163
		summarizeBy: sum
		sourceColumn: GDP Change

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'GDP per capita'
		dataType: string
		lineageTag: c22003f6-4e27-4516-8013-6a4667891dd0
		summarizeBy: none
		sourceColumn: GDP per capita

		annotation SummarizationSetBy = Automatic

	column 'Pupil Teacher Ratio'
		dataType: string
		lineageTag: b5bea0f6-41b6-4454-bda4-4cf20db8f516
		summarizeBy: none
		sourceColumn: Pupil Teacher Ratio

		annotation SummarizationSetBy = Automatic

	column 'Pupil Teacher Ratio Change'
		dataType: int64
		formatString: 0
		lineageTag: 8ffd0169-1554-41f1-8caa-19cb5b2c2de7
		summarizeBy: sum
		sourceColumn: Pupil Teacher Ratio Change

		annotation SummarizationSetBy = Automatic

	column 'Tuberculosis Incidents Change'
		dataType: int64
		formatString: 0
		lineageTag: c9e141d1-dae4-4fba-880f-02285ba8037d
		summarizeBy: sum
		sourceColumn: Tuberculosis Incidents Change

		annotation SummarizationSetBy = Automatic

	column 'Tuberculosis Incidents'
		dataType: string
		lineageTag: 2bf2b8c9-3db0-4e14-81b1-0e8aed57ad5b
		summarizeBy: none
		sourceColumn: Tuberculosis Incidents

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 4fd16668-f85d-43db-8ce0-b3cb89060495
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column 'Measles Vaccine'
		dataType: string
		lineageTag: a6415dbc-97a5-4f78-b5d2-3dd9069a628e
		summarizeBy: none
		sourceColumn: Measles Vaccine

		annotation SummarizationSetBy = Automatic

	column 'Measles Vaccines'
		dataType: string
		lineageTag: 24c14b06-8905-4895-815d-86b77a121995
		summarizeBy: none
		sourceColumn: Measles Vaccines

		annotation SummarizationSetBy = Automatic

	column 'Hib3 Immunizations %'
		dataType: string
		lineageTag: 438bd1cc-fc59-4cee-926f-caf3197d0bf3
		summarizeBy: none
		sourceColumn: Hib3 Immunizations %

		annotation SummarizationSetBy = Automatic

	column 'Hib3 Immunizations'
		dataType: string
		lineageTag: f8682544-0deb-4588-93f4-069e7d8900d7
		summarizeBy: none
		sourceColumn: Hib3 Immunizations

		annotation SummarizationSetBy = Automatic

	column 'Water Services'
		dataType: string
		lineageTag: 2bd0163f-e286-4312-a787-1d84d3044715
		summarizeBy: none
		sourceColumn: Water Services

		annotation SummarizationSetBy = Automatic

	column 'Water Services Access'
		dataType: string
		lineageTag: 522c6452-23bb-42fa-9383-0e86a9dfe55e
		summarizeBy: none
		sourceColumn: Water Services Access

		annotation SummarizationSetBy = Automatic

	partition 'Variance Analysis-50fc48d8-b6b5-42bc-915e-5c9b370112ca' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Justyna\OneDrive - Microsoft\Gartner\BI Bake Off\London\Decomp Tree Metrics.csv"),[Delimiter=",", Columns=19, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Maternal Mortality Change", Int64.Type}, {"Maternal Mortality", type text}, {"Malaria Cases Change", Int64.Type}, {"Malaria Cases", type text}, {"Neonatal Mortality", Int64.Type}, {"Neonatal Mortality_1", type text}, {"GDP Change", type number}, {"GDP per capita Change", type text}, {"Pupil Teacher Ratio", type text}, {"Pupil Teacher Ratio Change", Int64.Type}, {"Tuberculosis Incidents", Int64.Type}, {"Tuberculosis Incidents_2", type text}, {"Country", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Neonatal Mortality", "Neonatal Mortality Change"}, {"Neonatal Mortality_1", "Neonatal Mortality"}, {"GDP per capita Change", "GDP per capita"}, {"Tuberculosis Incidents", "Tuberculosis Incidents Change"}, {"Tuberculosis Incidents_2", "Tuberculosis Incidents"}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns","",null,Replacer.ReplaceValue,{"Maternal Mortality"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","",null,Replacer.ReplaceValue,{"Malaria Cases"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","",null,Replacer.ReplaceValue,{"Pupil Teacher Ratio"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","",null,Replacer.ReplaceValue,{"Tuberculosis Incidents"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","",null,Replacer.ReplaceValue,{"GDP per capita"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Replaced Value4",{{"Hib3 Immunizations", "Hib3 Immunizations %"}, {"Hib3 Immunizations_3", "Hib3 Immunizations"}, {"Water Services Access", "Water Services"}, {"Water Services Access_4", "Water Services Access"}})
				in
				    #"Renamed Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

