table Year
	lineageTag: 2dd08857-ddd2-47ae-b4f7-616ae54eb678

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 5a7a90ad-1f07-4fc3-a345-5ca1c49ccd5a
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8691aec3-865c-4eca-94bd-d4260d83160f
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: af7cdcad-c7ce-42fc-88e8-db4ff74e4221
			defaultHierarchy: LocalDateTable_021b8805-3ede-4d55-9182-0236ac5e0923.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Year-23e82efd-b70c-4cfd-b750-b48b9204417e = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Justyna\OneDrive - Microsoft\Gartner\BI Bake Off\London\Year.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Year", Int64.Type}}),
				    #"Inserted Date" = Table.AddColumn(#"Changed Type", "Date", each Date.From(Text.From([Year], "en-US")), type date)
				in
				    #"Inserted Date"

	annotation PBI_QueryRelationships = {"columnCount":1,"keyColumnNames":[],"queryRelationships":[],"columnIdentities":["Section1/Year/Changed Type.{Year,0}"],"ColumnCount":1,"KeyColumnNames":[],"ColumnIdentities":["Section1/Year/Changed Type.{Year,0}"],"RelationshipInfo":[]}

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

